# Generated by Django 2.2.3 on 2019-07-04 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('product_ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ref_id', to='productCreator.Productss')),
                ('question_ref_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_ref_id', to='productCreator.Attributess')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField(max_length=500)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='productCreator.Productss')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='productCreator.Questions')),
            ],
        ),
        migrations.AddField(
            model_name='attributess',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='productCreator.Productss'),
        ),
    ]
