# Generated by Django 2.2.3 on 2019-07-04 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productCreator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributess',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Productss', to='productCreator.Productss'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='choice',
            field=models.CharField(choices=[('5', 'Me gusta'), ('4', 'Deberia estar presente'), ('3', 'Soy Neutral'), ('2', 'Podria vivir con eso'), ('1', 'NO me gusta')], max_length=2),
        ),
        migrations.AlterField(
            model_name='questions',
            name='product_ref_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_ref_id', to='productCreator.Productss'),
        ),
    ]
