# Generated by Django 2.2.3 on 2019-07-04 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productCreator', '0005_remove_questions_product_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='product_ref_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_ref_id', to='productCreator.Productss'),
            preserve_default=False,
        ),
    ]
