# Generated by Django 2.2.3 on 2019-07-04 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productCreator', '0006_questions_product_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='productCreator.Productss'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='question_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='productCreator.Questions'),
        ),
    ]
