# Generated by Django 2.2.3 on 2019-07-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productCreator', '0007_auto_20190704_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_ref_id',
        ),
        migrations.AddField(
            model_name='questions',
            name='attributes_ref_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='productCreator.Attributess'),
            preserve_default=False,
        ),
    ]
