# Generated by Django 2.2.3 on 2019-07-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productCreator', '0008_auto_20190704_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='attribute_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_ref_id', to='productCreator.Attributess'),
            preserve_default=False,
        ),
    ]
