# Generated by Django 2.2.3 on 2019-07-04 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productCreator', '0010_auto_20190704_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='attributes_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='productCreator.Attributess'),
        ),
    ]
