# Generated by Django 2.2.3 on 2019-07-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCreator', '0020_auto_20190709_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='choice',
            field=models.CharField(choices=[('Me gusta', 'Me gusta'), ('Deberia estar presente', 'Deberia estar presente'), ('Soy Neutral', 'Soy Neutral'), ('Podria vivir con ello', 'Podria vivir con eso'), ('No me gusta', 'NO me gusta')], max_length=40),
        ),
    ]
